name: Scheduled update of song lyrics daily

# This workflow will trigger every 5 minutes.
# To adjust the schedule, modify the cron expression.
on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update_song_lyrics:
    runs-on: ubuntu-latest
    container:
      image: python:3.8
    steps:
      # Step 1: Check out your repository
      - uses: actions/checkout@v3
      # Step 2: Install dependencies in requirements.txt
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Step 3: Download from Google Drive
      - name: Download from Google Drive
        uses: satackey/action-google-drive@v1
        with:
          skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
          download-from: '/EasyslidesData/Admin/Databases/' 
          download-to: '${{ github.workspace }}' # Adjust the path if needed

      # Step 4: (Optional) Modify the downloaded file
      - name: Process the downloaded file
        run: cd ${{ github.workspace }} && python convert_sql2docx.py

      # Step 5: Upload to Google Drive 
      - name: Upload to Google Drive 
        uses: satackey/action-google-drive@v1
        with:
          skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
          upload-from: '${{ github.workspace }}' 
          upload-to: '/ARCHIVED/test_github_action/' # Or the path to the modified file

      # **IMPORTANT: Set up secrets**
      # You'll need to create secrets in your repository's settings to store 
      # sensitive credentials for Google Drive authentication. 
      # Refer to the documentation of the individual actions for details.