name: Scheduled update of song lyrics daily

# This workflow will trigger every day at 0h30 GMT+7.
# To adjust the schedule, modify the cron expression.
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 17 * * SAT'

jobs:
  update_song_lyrics:
    runs-on: ubuntu-latest
    container:
      image: python:3.8
    steps:
      # Step 1: Check out your repository
      - uses: actions/checkout@v4
      # Step 2: Install dependencies in requirements.txt
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Step 3: Setup rclone and Download from Google Drive
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
          version: v1.65.1
      
      - name: Add Rclone service account file
        uses: AnimMouse/setup-rclone/service-account-file@v1
        with:
          service_account_filename: service-account-file.json
          service_account_file: ${{ secrets.SERVICE_ACCOUNT_FILE }}

      - name: Download from Google Drive
        env:
            RCLONE_DRIVE_SERVICE_ACCOUNT_FILE: ~/.config/rclone/service-account-file.json
        run: rclone copy --drive-root-folder-id 19RMEET6ArmcaRWPtqbDPia4ITZfnQ2Uj ANGC_gdrive:Admin/Databases/Dedupe_Pooled_Database_2023_curated.db ./download_db/ -P

      # Step 4: Modify the downloaded file
      - name: Process the downloaded file
        run: python convert_sql2docx.py

      # Step 5: Upload to Google Drive 
      - name: Upload to Google Drive
        env:
            RCLONE_DRIVE_SERVICE_ACCOUNT_FILE: ~/.config/rclone/service-account-file.json
        run: rclone copy --drive-root-folder-id 1-vqA0oX3GXE3EYhodg_FvPiAL1Ua-oZJ ./output/ ANGC_gdrive:/ -P

      # **IMPORTANT: Set up secrets**
      # You'll need to create secrets in your repository's settings to store 
      # sensitive credentials for Google Drive authentication. 
      # Refer to the documentation of the individual actions for details.
